version: '3.6'
services:
  fe:
    image: maslow123/books-client:latest
    build:
      context: .
      dockerfile: docker/fe/Dockerfile
    container_name: fe
    ports:
     - 3000:3000  
networks:
  books:
    driver: bridge